src/main/cpp/Robot.cpp, src/main/cpp/subsystems/Climber.cpp, src/main/include/Constants.hpp, src/main/include/Robot.hpp, src/main/include/subsystems/Climber.hpp
This is the subsystem for the climber system with their correct ports assigned to them. This was previously another pull request, but it was later corrupted. This is to serve as its replacement.
=> Create the Climber Subsystem

src/test/cpp/frc/trajectory/MaxVelocityConstraintTest.cpp, src/test/cpp/frc/trajectory/RegionConstraintTest.cpp, src/test/include/frc/.clang-format, src/test/include/frc/.styleguide, src/test/include/frc/.styleguide-license, src/test/include/frc/trajectory/TestTrajectory.h, thirdparty/include/frc/trajectory/constraint/MaxVelocityConstraint.h, thirdparty/include/frc/trajectory/constraint/RegionConstraint.h
This constraint applies an arbitrary constraint only within a rectangular
region of pose.
=> Add drivetrain trajectory region constraint

src/main/cpp/subsystems/Intake.cpp
Adds the logic to stop the funnel from intaking when the top sensor of the conveyor is triggered.
=> Stop funnel when full

src/main/cpp/Robot.cpp, src/main/cpp/subsystems/Flywheel.cpp, src/main/cpp/subsystems/Intake.cpp, src/main/include/subsystems/Flywheel.hpp
=> Refactor intake logic

intake-io-table.md, src/main/cpp/Robot.cpp, src/main/cpp/subsystems/Flywheel.cpp, src/main/cpp/subsystems/Intake.cpp, src/main/include/Robot.hpp, src/main/include/subsystems/Flywheel.hpp
=> Rewrite intake logic based on input-output table

README.md, src/main/cpp/LiveGrapherControllerLogger.cpp, src/main/cpp/livegrapher/ClientConnection.cpp, src/main/cpp/livegrapher/LiveGrapher.cpp, src/main/cpp/livegrapher/Pipe.cpp, src/main/cpp/livegrapher/Socket.cpp, src/main/cpp/livegrapher/SocketSelector.cpp, src/main/cpp/livegrapher/TcpListener.cpp, src/main/cpp/livegrapher/TcpSocket.cpp, src/main/include/CSVControllerLogger.hpp, src/main/include/LiveGrapherControllerLogger.hpp, src/main/include/controllers/ControllerBase.hpp, src/main/include/livegrapher/ClientConnection.hpp, src/main/include/livegrapher/LiveGrapher.hpp, src/main/include/livegrapher/Pipe.hpp, src/main/include/livegrapher/Protocol.hpp, src/main/include/livegrapher/Socket.hpp, src/main/include/livegrapher/SocketSelector.hpp, src/main/include/livegrapher/TcpListener.hpp, src/main/include/livegrapher/TcpSocket.hpp
=> Add LiveGrapher backend to ControllerBase logging

src/main/cpp/Robot.cpp, src/main/cpp/autonomous/AutoLeftSideIntake.cpp, src/main/cpp/autonomous/AutoLoadingZoneDriveForward.cpp, src/main/cpp/autonomous/AutoLoadingZoneShootThree.cpp, src/main/cpp/autonomous/AutoRightSideDriveForward.cpp, src/main/cpp/autonomous/AutoRightSideIntake.cpp, src/main/cpp/autonomous/AutoRightSideShootSix.cpp, src/main/cpp/autonomous/AutoRightSideShootThree.cpp, src/main/cpp/autonomous/AutoTargetZoneShootSix.cpp, src/main/cpp/autonomous/AutoTargetZoneShootThree.cpp, src/main/include/subsystems/Drivetrain.hpp
Reorganize code so that we intake only in the region that we specify.
Deploy the intake in the autnomous modes. Lower timeout on conveyor and
funnel when shooting. Make sure each autonomous mode finishes on time.
Closes #98, Closes #100
=> Make sure autonomous modes are written correctly

src/main/cpp/frc/trajectory/constraint/DifferentialDriveVelocitySystemConstraint.cpp, src/test/cpp/frc/trajectory/constraint/DifferentialDriveVelocitySystemTest.cpp
The previous max velocity constraint was using the current chassis
velocity instead of the model's max velocity.
Fixes #108.
=> Drivetrain trajectories now take corners faster

src/main/cpp/autonomous/AutoLeftSideIntake.cpp, src/main/cpp/autonomous/AutoRightSideIntake.cpp, src/main/cpp/autonomous/AutoRightSideShootSix.cpp
Had problems intaking inside region constraint so intake until
drivetrain reaches goal
=> Remove intaking in region constraint

docs/flywheel-ball-dynamics.md, src/main/cpp/IntakeSim.cpp, src/main/cpp/Robot.cpp, src/main/cpp/autonomous/AutoLoadingZoneShootThree.cpp, src/main/cpp/autonomous/AutoRightSideShootSix.cpp, src/main/cpp/autonomous/AutoRightSideShootThree.cpp, src/main/cpp/autonomous/AutoTargetZoneShootSix.cpp, src/main/cpp/autonomous/AutoTargetZoneShootThree.cpp, src/main/cpp/controllers/FlywheelController.cpp, src/main/cpp/subsystems/Flywheel.cpp, src/main/cpp/subsystems/Intake.cpp, src/main/include/IntakeSim.hpp, src/main/include/Robot.hpp, src/main/include/controllers/FlywheelController.hpp, src/main/include/subsystems/Flywheel.hpp, src/main/include/subsystems/Intake.hpp, src/test/cpp/RobotTest.cpp
This lets the autonomous modes complete faster than if a timeout alone
was used.
=> Shoot a more specific number of balls in autonomous

src/main/cpp/subsystems/Drivetrain.cpp, src/main/include/rev/CANSparkMax.hpp
=> Add current limit for drivetrain motors

src/main/cpp/ADCInput.cpp, src/main/cpp/subsystems/Turret.cpp, src/main/include/ADCInput.hpp, src/main/include/subsystems/Turret.hpp
=> Add wrapper class provides DigitalInput interface for AnalogInput

src/main/include/controllers/DrivetrainController.hpp
Updates the current Wheel Radius value in the DrivetrainController heading.
=> Update kWheelRadius value in DrivetrainController

.styleguide, docs/drivetrain-imu-measurement-model.md, src/main/cpp/adi/ADIS16470_IMU.cpp, src/main/cpp/adi/simulation/ADIS16470_IMUSim.cpp, src/main/cpp/controllers/DrivetrainController.cpp, src/main/cpp/subsystems/Drivetrain.cpp, src/main/include/adi/ADIS16470_IMU.h, src/main/include/adi/simulation/ADIS16470_IMUSim.h, src/main/include/controllers/DrivetrainController.hpp, src/main/include/subsystems/Drivetrain.hpp, src/test/cpp/DrivetrainTest.cpp
=> Add IMU acceleration to drivetrain measurement model

src/main/cpp/NetworkTableUtil.cpp, src/main/include/NetworkTableUtil.hpp, src/main/include/Robot.hpp, src/main/include/subsystems/Climber.hpp, src/main/include/subsystems/Drivetrain.hpp, src/main/include/subsystems/Flywheel.hpp, src/main/include/subsystems/Intake.hpp, src/main/include/subsystems/Turret.hpp, src/main/include/subsystems/Vision.hpp, src/test/cpp/VisionTest.cpp
Correct the default value in networktables from a boolean to a
double
=> Fix default value overloads for NetworkTables entries

src/main/cpp/Robot.cpp, src/main/cpp/autonomous/AutoNavBarrelRacing.cpp, src/main/include/Robot.hpp
Creates an auton mode for navigating the Barrel Racing Path as part of the AutoNav Challenge.
**_Current Status:_**
**WIP**
=> Add autonomous mode for Barrel Racing path

src/main/cpp/Robot.cpp, src/main/cpp/autonomous/AutoNavSlalom.cpp, src/main/include/Robot.hpp
Creates autonomous mode for the Slalom Path from the AutoNav Challenge.
=> Add autonomous mode for Slalom Path

src/main/cpp/Robot.cpp
I wasn't sure if it was better to duplicate code or to do this so I chose this instead.
=> Allow shooting in test mode

src/main/cpp/autonomous/AutoNavBarrelRacing.cpp
Tweaks the waypoints for the Barrel Racing Path to ensure robot completes them.
=> Tweak Barrel Racing for official competition recording

src/main/cpp/rev/ColorSensorV3.cpp, src/main/cpp/subsystems/Climber.cpp, src/main/include/HWConfig.hpp, src/main/include/rev/ColorMatch.hpp, src/main/include/subsystems/Climber.hpp, src/test/cpp/ClimberTest.cpp, vendordeps/REVColorSensorV3.json
Co-authored-by: KyleQ1 <kylequinlan09@gmail.com>
Co-authored-by: Tyler Veness <calcmogul@gmail.com>
=> Implement control panel arm

src/main/cpp/Robot.cpp, src/main/cpp/autonomous/AutoLeftSideIntake.cpp, src/main/cpp/autonomous/AutoLeftSideShootTen.cpp, src/main/cpp/autonomous/AutoLoadingZoneShootThree.cpp, src/main/cpp/autonomous/AutoRightSideDriveForward.cpp, src/main/cpp/autonomous/AutoRightSideShootEight.cpp, src/main/cpp/autonomous/AutoRightSideShootSix.cpp, src/main/cpp/autonomous/AutoShootNine.cpp, src/main/cpp/autonomous/AutoShootThree.cpp, src/main/cpp/autonomous/AutoTargetZoneShootSix.cpp, src/main/cpp/autonomous/AutoTargetZoneShootThree.cpp, src/main/cpp/controllers/DrivetrainController.cpp, src/main/cpp/subsystems/Flywheel.cpp, src/main/cpp/subsystems/Intake.cpp, src/main/include/Constants.hpp, src/main/include/Robot.hpp, src/main/include/controllers/TurretController.hpp, src/test/cpp/RobotTest.cpp
Tweak Auton modes for the 2021 version of the Infinite Recharge game. 
Also allow them to utilize the new vision shooting system
=> Tweak Auton Modes for the 2021 game of Infinite Recharge
